### ISSUE TITLE
Accepting pull requests?

### ISSUE THREAD

**Issue by shirish93** [ParallelDots/WordEmbeddingAutoencoder#2]
Hi!

I cleaned up the code a bit, made it work with Python3, and made it more pythonic. Would you consider accepting a pull request, or would the effort be not worth it?

I realize this is an academic endeavor, so I can understand if there's not as much interest in active code maintenance ;)

Do let me know!

-Shirish

**Comment by mAch17** [comment]
Sure. Please send it.
